server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        proxy_pass http://api-gateway:8000/health;
    }

    location /predict {
        proxy_pass http://api-gateway:8000/predict;
    }

    location /predict-support {
        proxy_pass http://api-gateway:8000/predict-support;
    }

    location /predict-segmentation {
        proxy_pass http://api-gateway:8000/predict-segmentation;
    }

    location /predict-anomaly {
        proxy_pass http://api-gateway:8000/predict-anomaly;
    }

    location /prioritize-interventions {
        proxy_pass http://api-gateway:8000/prioritize-interventions;
    }
}
